version: "3.9"

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    env_file:
      - /var/lib/jenkins/workspace/Front_end_Pipeline/vue-project/.env
    volumes:
      - /var/lib/jenkins/workspace/Front_end_Pipeline/vue-project/dist:/usr/share/nginx/html
